Modified container initialization to get system settings using an API call.

diff --git a/rootfs/etc/cont-init.d/00-25-mailcatcher b/rootfs/etc/cont-init.d/00-25-mailcatcher
--- a/rootfs/etc/cont-init.d/00-25-mailcatcher
+++ b/rootfs/etc/cont-init.d/00-25-mailcatcher
@@ -8,10 +8,35 @@ if [ -z "$DASPANEL_SYS_UUID" ]; then
     exit 1
 fi
 
+case "$DASPANEL_WAIT_FOR_API" in
+    YES|yes|Yes)
+        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
+        /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
+        result=$?
+        if [ ! $result -eq 0 ] ; then
+            echo "[DASPANEL] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
+            exit 1
+        fi
+        ;;
+    *) 
+        echo "[DASPANEL] Container not need to wait API become online: $0" >&2
+        exit 1
+        ;;
+esac
+
+# Get system configs from API server and set env variables
+SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
+result=$?
+if [ ! $result -eq 0 ] ; then
+    echo "[DASPANEL] Unable to get tenant configuration from API server: $0" >&2
+    exit 1
+fi
+export DASPANEL_SMTP_PASSWORD=`echo $SYSCFG | /usr/bin/jq -r '.smtp.password'`
+
 mkdir -p /etc/daspanel/mailhog
 
-TXTPWD=`cat /opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json | /usr/bin/jq -r '.smtp.password'`
-CATCH_PWD=`mailhog bcrypt $TXTPWD; echo` /usr/bin/gomplate -d cfg=file:///opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json \
+CATCH_PWD=`mailhog bcrypt $DASPANEL_SMTP_PASSWORD; echo` /usr/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
+    -H "cfg=Authorization: $DASPANEL_SYS_APIKEY" \
     < /opt/daspanel/conf-templates/mailhog/auth.db.tmpl \
     >  /etc/daspanel/mailhog/auth.db    
 
